"""讲习班名称、路径和数据生成规模的单一事实来源。
Single source of truth for workshop names, paths and data-generation sizes."""

from __future__ import annotations

from dataclasses import dataclass

DEFAULT_SERVERS: tuple[str, ...] = ("mt5-sg-01", "mt5-sg-02", "mt5-uk-01", "mt5-cy-01")

# 每个服务器的元数据。setup 不生成 ``mt5-hk-01``: 滴灌程序 (drip producer)
# 在 Lakeflow 作业讲习班期间实时"登录"它（新服务器场景）。
# Per-server metadata. ``mt5-hk-01`` is not generated by setup: the drip producer
# "onboards" it live during the Lakeflow Jobs lab (new-server scenario).
SERVER_META: dict[str, dict] = {
    "mt5-sg-01": {
        "region": "SEA",
        "brands": {"Apex": 0.7, "Nova": 0.3},
        "login_base": 81_000_000,
        "deal_base": 1_100_000_000,
        "position_base": 2_100_000_000,
        "countries": {"MY": 30, "SG": 12, "TH": 14, "VN": 14, "ID": 12, "PH": 8, "HK": 5, "TW": 5},
    },
    "mt5-sg-02": {
        "region": "APAC",
        "brands": {"Apex": 1.0},
        "login_base": 82_000_000,
        "deal_base": 1_200_000_000,
        "position_base": 2_200_000_000,
        "countries": {"MY": 20, "SG": 10, "AU": 18, "TH": 10, "VN": 10, "ID": 10, "PH": 6, "JP": 8, "KR": 8},
    },
    "mt5-uk-01": {
        "region": "EMEA",
        "brands": {"Orion": 1.0},
        "login_base": 83_000_000,
        "deal_base": 1_300_000_000,
        "position_base": 2_300_000_000,
        "countries": {"GB": 25, "DE": 12, "FR": 8, "ES": 8, "IT": 8, "AE": 15, "SA": 6, "ZA": 10, "NG": 8},
    },
    "mt5-cy-01": {
        "region": "EU-LATAM",
        "brands": {"Nova": 0.6, "Orion": 0.4},
        "login_base": 84_000_000,
        "deal_base": 1_400_000_000,
        "position_base": 2_400_000_000,
        "countries": {"CY": 5, "GR": 8, "PL": 10, "BR": 22, "MX": 18, "CO": 10, "CL": 7, "AR": 10, "TR": 10},
    },
    "mt5-hk-01": {
        "region": "GCR",
        "brands": {"Apex": 0.5, "Nova": 0.5},
        "login_base": 85_000_000,
        "deal_base": 1_500_000_000,
        "position_base": 2_500_000_000,
        "countries": {"HK": 40, "TW": 30, "MO": 10, "SG": 10, "MY": 10},
    },
}

MT5_TABLES: tuple[str, ...] = ("mt5_users", "mt5_deals", "mt5_positions")


@dataclass(frozen=True)
class WorkshopConfig:
    catalog: str = "hytech_de_workshop"
    raw_schema: str = "raw"
    solutions_schema: str = "solutions"
    ops_schema: str = "ops"
    participant_group: str = "de_workshop_sz"
    llm_endpoint: str = "databricks-claude-sonnet-4-5"
    servers: tuple[str, ...] = DEFAULT_SERVERS
    seed: int = 42
    history_days: int = 90  # days of deals before the CDC window
    cdc_window_hours: int = 48  # hourly CDC files between the full load (T0) and "now"
    users_per_server: int = 1500
    positions_per_server_per_day: int = 1400
    event_days: int = 7
    events_per_day: int = 20_000
    volume_root: str | None = None  # override (local tests): replaces /Volumes/<catalog>/<raw_schema>

    @property
    def raw_root(self) -> str:
        return self.volume_root or f"/Volumes/{self.catalog}/{self.raw_schema}"

    @property
    def landing_root(self) -> str:
        return f"{self.raw_root}/landing"

    @property
    def ref_root(self) -> str:
        return f"{self.raw_root}/ref"

    @property
    def producer_root(self) -> str:
        return f"{self.raw_root}/producer"

    @property
    def events_dir(self) -> str:
        return f"{self.landing_root}/app_events"

    def mt5_dir(self, server: str, table: str) -> str:
        return f"{self.landing_root}/mt5/{server}/{table}"


def participant_schema(user_name: str) -> str:
    """每个参与者的 schema 名称，例如 ``zhihan.tan@databricks.com`` -> ``u_zhihan_tan``。
    Per-participant schema name, e.g. ``zhihan.tan@databricks.com`` -> ``u_zhihan_tan``."""
    local = user_name.split("@")[0].lower()
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in local).strip("_")
    return f"u_{cleaned}"
